name: Deploy pages

on:
  workflow_dispatch: { }
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build 1st
        run: npm run build -- 01-js-intro.md --out=dist/01-js-intro --base=/itmo-js/01-js-intro/

      - name: Build 2nd
        run: npm run build -- 02-basic-syntax.md --out=dist/02-basic-syntax --base=/itmo-js/02-basic-syntax/

      - name: Build 3d
        run: npm run build -- 03-objects.md --out=dist/03-objects --base=/itmo-js/03-objects/

      - name: Create root navigation file
        run: cp index.html dist/index.html

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
